# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3

  - name: session_name
    type: string

  - name: experimenter
    type: string

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "Subject ID (three digits)"
    session_name: "Session Name"
    experimenter: "Experimenter"
    gender: "Gender"
    registration_failed: "Registration failed."
    registration_successful: "Registration successful！"
    invalid_input: "Field {field} input is invalid."


# === Window settings ===
window:
  size: [1920, 1080]
  monitor: testMonitor
  units: deg
  screen: 1
  bg_color: gray
  fullscreen: True

# === Task-level settings ===
task:
  total_blocks: 2
  total_trials: 10
  trial_per_block: 5
  conditions: [go_left, go_right, stop_left, stop_right]
  key_list: [left, right]
  seed_mode: "same_across_sub"


# === Stimuli (for MID task) ===
stimuli:
  fixation:
    type: text
    text: "+"
    color: white
  go_left:
    type: shape
    vertices:
      - [ 0.20,  0.05]
      - [ 0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [-0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: white
    size: 8
    lineColor: ''

  go_right:
    type: shape
    vertices:
      - [-0.20,  0.05]
      - [-0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [ 0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: white
    size: 8
    lineColor: ''

  stop_left:
    type: shape
    vertices:
      - [ 0.20,  0.05]
      - [ 0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [-0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: red
    size: 8
    lineColor: ''

  stop_right:
    type: shape
    vertices:
      - [-0.20,  0.05]
      - [-0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [ 0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: red
    size: 8
    lineColor: ''
  blank:
    type: text
    text: ''
    color: gray
  
  block_break:
    type: text
    text: |
      Take a break! 
      When you are ready, press space to continue.
    color: white

  block_feedback:
    type: text
    text: |
      Block {block_num} of {total_blocks} completed. 
      Accuaracy: {accuracy:.2f}
      Reward: {reward:.2f}
      Press space to continue.
    color: white

  instruction_text:
    type: text
    text: |
      In this task, you will see a series of cues and targets. 
      Your task is to respond to the cues as quickly as possible. 
      If you respond to a cue, you will earn 10 points. 
      If you do not respond to a cue, you will earn 0 points. 
      Press space to continue.
    color: white


  good_bye:
    type: text
    text: |
      Thank you for participating!
      Press space to exit.
    color: white

# === Timing & Adaptivity ===
timing:
  fixation_duration: [0.5, 0.8]
  go_duration: 1.0        # how long the arrow is on screen (seconds)

# === Triggers ===
triggers:
  exp_onset: 98
  exp_end: 99

  block_onset: 100
  block_end: 101

  fixation_onset: 1

  go_onset: 10
  go_response: 11
  go_miss: 12
  pre_stop_response: 23
  on_stop_response: 24
  post_stop_response: 25


# === Controller ===
controller:
  initial_ssd: 0.25             # initial stop‐signal delay (in seconds)
  step: 0.05            # staircase step size (in whatever units you define)
  min_ssd: 0.05
  max_ssd: 0.5
  target_success: 0.5  # 1-up 1-down

